#!/bin/bash

CONFIGURATION=./configuration.conf

while read line; do
    if [[ $line =~ ^"["(.*)"]"$ ]] ; then
        array=${BASH_REMATCH[1]}
        declare -A ${array}
    elif [[ $line =~ ^([_[:alnum:]]*)"="(.*) ]] ; then
        if ! [ -v ${array} ] ; then
          declare ${array}[${BASH_REMATCH[1]}]="${BASH_REMATCH[2]}"
        fi
    fi
done < $CONFIGURATION
